# Nom du fichier : .github/workflows/terraform-iac.yml

name: "IAC: Deploy Infrastructure (Secure & Modern)"


on:

  push:
    branches: 
      - main 
    paths: 
      - 'terraform/**'
      - '.github/workflows/terraform-iac.yml'
  pull_request:
    branches: 
      - main 
    paths: 
      - 'terraform/**'
      - '.github/workflows/terraform-iac.yml'
      
  # ===================================================================
  # MODIFICATION 1: Ajout d'entrées pour le déclenchement manuel
  # ===================================================================
  workflow_dispatch:
    inputs:
      action:
        description: 'Action à exécuter : "apply" ou "destroy"'
        required: true
        default: 'apply'
        type: choice
        options:
        - apply
        - destroy
      
      # Ajout d'une confirmation pour l'action de destruction
      confirm_destroy:
        description: 'Tapez "destroy-confirm" pour confirmer la destruction. (Obligatoire si action=destroy)'
        required: false # Rendu obligatoire par la logique du job plus bas

jobs:
  terraform:
    name: "Terraform Plan, Apply & Destroy"
    runs-on: ubuntu-latest
    
    
    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
    - name: Checkout source code 
      uses: actions/checkout@v4



    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.7

    - name: Configure AWS Credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::228578233417:role/oicd
        aws-region: us-east-1

    - name: Terraform Init
      id: init
      run: terraform init  

    - name: Terraform Plan
      id: plan
      # Le plan s'exécute toujours pour voir les changements, même avant une destruction.
      run: terraform plan -no-color -input=false -out=planfile -lock=false

    # ===================================================================
    # MODIFICATION 2: L'étape Apply ne s'exécute que si l'action est "apply"
    # ===================================================================
    - name: "Terraform Apply"
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply'
      run: terraform apply -auto-approve -input=false planfile -lock=false

    # ===================================================================
    # MODIFICATION 3: Nouvelle étape pour la destruction, avec double confirmation
    # ===================================================================
    - name: "Terraform Destroy (DANGEROUS)"
      if: |
        github.event_name == 'workflow_dispatch' &&
        github.event.inputs.action == 'destroy' &&
        github.event.inputs.confirm_destroy == 'destroy-confirm'
      run: terraform destroy -auto-approve -lock=false
