
name: "IAC: Deploy Infrastructure (Secure & Modern)"

on:
  push:
    branches: 
      - main 
    paths: 
      - 'terraform/**'
      - '.github/workflows/terraform-iac.yml'
  pull_request:
    branches: 
      - main 
    paths: 
      - 'terraform/**'
      - '.github/workflows/terraform-iac.yml'
      
  workflow_dispatch:
    inputs:
      action:
        description: 'Action à exécuter : "apply" ou "destroy"'
        required: true
        default: 'apply'
        type: choice
        options:
        - apply
        - destroy
      
      confirm_destroy:
        description: 'Tapez "destroy-confirm" pour confirmer la destruction. (Obligatoire si action=destroy)'
        required: false

jobs:
  security_scan:
    name: "Security: Scan IaC with Checkov"
    runs-on: ubuntu-latest
    permissions:
      contents: read 

    steps:
    - name: Checkout source code 
      uses: actions/checkout@v4

    - name: Run Checkov scan and generate JSON report
      uses: bridgecrewio/checkov-action@master
      with:
        directory: ./terraform
        framework: terraform
        output_format: json
        output_file_path: checkov-iac-report.json
        soft_fail: true

    - name: Upload Checkov JSON report as artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: checkov-iac-report-json
        path: checkov-iac-report.json

  terraform:
    name: "Terraform Plan, Apply & Destroy"
    runs-on: ubuntu-latest
    needs: security_scan # Dépend du succès du scan de sécurité

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
    - name: Checkout source code 
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.7

    - name: Configure AWS Credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
          role-to-assume: arn:aws:iam::228578233417:role/oicd
          aws-region:  us-east-1

    - name: Terraform Init
      id: init
      run: terraform init  

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false -out=planfile  -lock=false

    - name: "Terraform Apply"
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply'
      run: terraform apply -auto-approve -input=false planfile 

    - name: "Terraform Destroy (DANGEROUS)"
      if: |
        github.event_name == 'workflow_dispatch' &&
        github.event.inputs.action == 'destroy' &&
        github.event.inputs.confirm_destroy == 'destroy-confirm'
      run: terraform destroy -auto-approve -lock=false
